### ISSUE TITLE
Update W & b error

### ISSUE THREAD

**Issue by Ricky-WL** [VinceShieh/spark-ffm#13]
![update_error](https://user-images.githubusercontent.com/814343/34606977-6e68d7ec-f24c-11e7-80a1-f2f757769b5d.png)

**Comment by VinceShieh** [comment]
Yes, it's obviously a bug here, but they should not be set to 1.0 also, since they are regularization params for bias, one-way interactions, and the "r" is regularization for pair-wise interactions, so the best solution is to group r0, r1, r into a 3 elements tuple - 'regParam' for instance, and user set the regularization params for each part of the weight when calling 'train'
Can you make a PR for this? Thanks.

**Comment by Ricky-WL** [comment]
Ok, I will make a PR .
Before it I just want to confirm that , as I know bias need not be regularized in many machine learning algorithms, 
So here need it add r0 for bias?

**Comment by VinceShieh** [comment]
Yes, I think you can get rid of that.

**Comment by VinceShieh** [comment]
BTW, can you help make another PR to add some automation tests with travis?
you can refer to https://github.com/Intel-bigdata/imllib-spark, also hosted by us. 
Thanks.

**Comment by VinceShieh** [comment]
before Travis is supported, please make sure you have done sufficient tests with these changes. :)

**Comment by Ricky-WL** [comment]
I have tested for all my commit.

**Comment by VinceShieh** [comment]
PR merged. Close issue now.
